name: Build macosx-x86_64 dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build macosx-aarch64 dependencies"]
    branches: [main]
    types: 
      - completed

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-macosx-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Install `luarocks-build-treesitter-parser` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser

      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        if: ${{ matrix.parsers.install_info.requires_generate_from_grammar }}
        with:
          crate: tree-sitter-cli

      - uses: actions/setup-node@v4
        if: ${{ matrix.parsers.install_info.requires_generate_from_grammar }}

      - name: Get tree-sitter ABI version
        run: |
          # NOTE: Neovim prints output to stderr
          ABI_VERSION=="$(nvim -u NORC -c 'lua print(vim.treesitter.language_version)' --headless +q 2>&1)"
          echo "TREE_SITTER_LANGUAGE_VERSION=$AVI_VERSION" >> $GITHUB_ENV

      - name: Get tree-sitter-parsers.json
        uses: actions/checkout@v4
        with: 
          repository: nvim-neorocks/nurr
          sparse-checkout: |
            tree-sitter-parsers.json
          path: nurr
      - name: Install tree-sitter parsers
        run: |
          langs=$(jq -r '.parsers[] | .lang' nurr/tree-sitter-parsers.json)
          for lang in $langs; do
            rm "tree-sitter-$lang-scm-1.macosx-x86_64.rock" || true
            luarocks --local --dev --lua-version=5.1 install "tree-sitter-$lang" scm \
              && luarocks pack "tree-sitter-$lang" \
              || luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
              || echo "tree-sitter-$lang has not been packaged yet"
          done
      - name: Install `rocks-treesitter.nvim` Package
        run: |
          luarocks --verbose --local --dev --lua-version=5.1 install rocks-treesitter.nvim scm
          luarocks --verbose pack rocks-treesitter.nvim
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
      - name: commit-macosx-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update macosx-x86_64 build artifacts"
          file_pattern: "*.rock manifest* index.html"
