name: Debug build win32-x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      # - name: Install Luarocks
      #   uses: hishamhm/gh-actions-luarocks@master
      #   with:
      #     luarocksVersion: "3.11.0"

      - name: Install luarocks with scoop
        uses: MinoruSekine/setup-scoop@v4
        with:
          buckets: main
          apps: luarocks

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #
      # - name: Install Lua and LuaRocks with hererocks
      #   run: |
      #     python -m pip install hererocks
      #     python -m hererocks env --lua 5.1 --luarocks latest

      # - name: Install tree-sitter CLI
      #   uses: baptiste0928/cargo-install@v3
      #   if: ${{ matrix.parsers.install_info.requires_generate_from_grammar }}
      #   with:
      #     crate: tree-sitter-cli

      # - uses: actions/setup-node@v4
      #   if: ${{ matrix.parsers.install_info.requires_generate_from_grammar }}


      - name: Install build dependencies
        run: |
          # . env/bin/activate
          luarocks --local --lua-version=5.1 install luafilesystem --server='https://nvim-neorocks.github.io/rocks-binaries/'
          luarocks --local --lua-version=5.1 install luarocks-build-treesitter-parser --server='https://nvim-neorocks.github.io/rocks-binaries/'

      - name: Install tree-sitter parser
        run: |
          luarocks --local --lua-version=5.1 install --dev tree-sitter-toml
